import Head from 'next/head';
import { Partytown } from '@builder.io/partytown/react';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Partytown Try</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Partytown debug={false} forward={['dataLayer.push']} />

        <script
          type="text/partytown"
          dangerouslySetInnerHTML={{
            __html: `
              document.getElementById('output-script').textContent = 'hello';
              document.body.classList.add('completed');
              console.log('hello from partytown');
              console.log('window: ', window.location.href);
            `,
          }}
        />

        <script type="text/partytown" src="https://www.googletagmanager.com/gtm.js?id=GTM-P2SJ37K8"></script>
          
      </Head>
      <Component {...pageProps} />
    </>
  );
}
